import { ExampleCard } from '../../../components/ExampleCard';
import { ExampleSection } from '../../../components/ExampleSection';
import { UnstyledSpinner } from '../../../core/components/UnstyledSpinner/UnstyledSpinner';

export const VariantExample = () => (
  <ExampleSection title="Variant">
    <ExampleCard>
      <UnstyledSpinner
        variant="none"
        color="neutral"
      >
        NONE
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="text"
        color="neutral"
      >
        TEXT
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="plain"
        color="neutral"
      >
        PLAIN
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="light"
        color="neutral"
      >
        LIGHT
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="surface"
        color="neutral"
      >
        SURFACE
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="solid"
        color="neutral"
      >
        SOLID
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="none"
        border
        color="neutral"
      >
        NONE-BORDER
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="text"
        border
        color="neutral"
      >
        TEXT-BORDER
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="plain"
        border
        color="neutral"
      >
        PLAIN-BORDER
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="light"
        border
        color="neutral"
      >
        LIGHT-BORDER
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="surface"
        border
        color="neutral"
      >
        SURFACE-BORDER
      </UnstyledSpinner>
      <UnstyledSpinner
        variant="solid"
        border
        color="neutral"
      >
        SOLID-BORDER
      </UnstyledSpinner>
    </ExampleCard>
  </ExampleSection>
);
