import { systemStyles } from '../../config/system-styles';
import type { Classes } from '../../types';
import { getBorder } from './border';
import { getColor } from './color';
import { mergeClasses } from './merge-classes';

export const styleUnstyledBox = (
  className: string,
  {
    theme = 'light',
    variant = 'solid',
    padding = 'unset',
    p = 'unset',
    px = 'unset',
    py = 'unset',
    pt = 'unset',
    pb = 'unset',
    pl = 'unset',
    pr = 'unset',
    margin = 'unset',
    m = 'unset',
    mx = 'unset',
    my = 'unset',
    mt = 'unset',
    mb = 'unset',
    ml = 'unset',
    mr = 'unset',
    border = 'auto',
    bx = 'unset',
    by = 'unset',
    bt = 'unset',
    bb = 'unset',
    bl = 'unset',
    br = 'unset',
    radius = 'unset',
    rt = 'unset',
    rb = 'unset',
    rl = 'unset',
    rr = 'unset',
    rtl = 'unset',
    rtr = 'unset',
    rbl = 'unset',
    rbr = 'unset',
    font = 'unset',
    color = 'unset',
    shadow = 'unset',
    gap = 'unset',
    gx = 'unset',
    gy = 'unset'
  }: Classes
) => {
  const { bgColor, textColor } = getColor(variant, color);

  return mergeClasses(
    systemStyles.padding.default.default[padding],
    systemStyles.padding.default.all[p],
    systemStyles.padding.default.x[px],
    systemStyles.padding.default.y[py],
    systemStyles.padding.default.t[pt],
    systemStyles.padding.default.b[pb],
    systemStyles.padding.default.l[pl],
    systemStyles.padding.default.r[pr],
    systemStyles.margin.default[margin],
    systemStyles.margin.all[m],
    systemStyles.margin.x[mx],
    systemStyles.margin.y[my],
    systemStyles.margin.t[mt],
    systemStyles.margin.b[mb],
    systemStyles.margin.l[ml],
    systemStyles.margin.r[mr],
    systemStyles.border.all[getBorder(variant, border)],
    systemStyles.border.x[bx],
    systemStyles.border.y[by],
    systemStyles.border.t[bt],
    systemStyles.border.b[bb],
    systemStyles.border.l[bl],
    systemStyles.border.r[br],
    systemStyles.radius.all[radius],
    systemStyles.radius.t[rt],
    systemStyles.radius.b[rb],
    systemStyles.radius.l[rl],
    systemStyles.radius.r[rr],
    systemStyles.radius.tl[rtl],
    systemStyles.radius.tr[rtr],
    systemStyles.radius.bl[rbl],
    systemStyles.radius.br[rbr],
    systemStyles.size.font[font],
    systemStyles.color.bg[theme][bgColor],
    systemStyles.color.text[theme][textColor],
    systemStyles.color.fill[theme][textColor],
    systemStyles.shadow[shadow],
    systemStyles.gap.all[gap],
    systemStyles.gap.x[gx],
    systemStyles.gap.y[gy],
    className
  );
};
