import type { ComponentConfig } from '../../types';
import type { TransitionConfigProps } from './Transition.types';

export const unstyledTransitionConfig: ComponentConfig<TransitionConfigProps> =
  {
    props: {
      as: 'div',
      unmountOnExit: false,
      peak: 'auto',
      transition: 'fade',
      duration: 1000,
      animationProps: {},
      variant: 'solid',
      padding: 'unset',
      p: 'unset',
      px: 'unset',
      py: 'unset',
      pt: 'unset',
      pb: 'unset',
      pl: 'unset',
      pr: 'unset',
      margin: 'unset',
      m: 'unset',
      mx: 'unset',
      my: 'unset',
      mt: 'unset',
      mb: 'unset',
      ml: 'unset',
      mr: 'unset',
      border: 'auto',
      bx: 'unset',
      by: 'unset',
      bt: 'unset',
      bb: 'unset',
      bl: 'unset',
      br: 'unset',
      radius: 'unset',
      rt: 'unset',
      rb: 'unset',
      rl: 'unset',
      rr: 'unset',
      rtl: 'unset',
      rtr: 'unset',
      rbl: 'unset',
      rbr: 'unset',
      font: 'unset',
      color: 'unset',
      shadow: 'unset',
      gap: 'unset',
      gx: 'unset',
      gy: 'unset'
    }
  };
