import { ExampleSection } from '../../../components/ExampleSection';
import { ExampleUnstyledTransition } from './ExampleUnstyledTransition';

export const SizeExample = () => (
  <ExampleSection title="Size">
    <ExampleUnstyledTransition
      light
      size="none"
    >
      NONE
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xs"
    >
      XS
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="sm"
    >
      SM
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="md"
    >
      MD
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="lg"
    >
      LG
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xl"
    >
      XL
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xxl"
    >
      XXL
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="none"
    >
      NONE
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xs-xs"
    >
      XS-XS
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="sm-sm"
    >
      SM-SM
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="md-md"
    >
      MD-MD
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="lg-lg"
    >
      LG-LG
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xl-xl"
    >
      XL-XL
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      light
      size="xxl-xxl"
    >
      XXL-XXL
    </ExampleUnstyledTransition>
  </ExampleSection>
);
