import { ExampleSection } from '../../../components/ExampleSection';
import { Example } from './Example';

export const VariantExample = () => (
  <ExampleSection title="Variant">
    <Example
      clear
      variant="none"
    >
      NONE
    </Example>
    <Example
      clear
      variant="text"
    >
      TEXT
    </Example>
    <Example
      clear
      variant="plain"
    >
      PLAIN
    </Example>
    <Example
      clear
      variant="light"
    >
      LIGHT
    </Example>
    <Example
      clear
      variant="surface"
    >
      SURFACE
    </Example>
    <Example
      clear
      variant="solid"
    >
      SOLID
    </Example>
    <Example
      clear
      variant="none"
      border
    >
      NONE-BORDER
    </Example>
    <Example
      clear
      variant="text"
      border
    >
      TEXT-BORDER
    </Example>
    <Example
      clear
      variant="plain"
      border
    >
      PLAIN-BORDER
    </Example>
    <Example
      clear
      variant="light"
      border
    >
      LIGHT-BORDER
    </Example>
    <Example
      clear
      variant="surface"
      border
    >
      SURFACE-BORDER
    </Example>
    <Example
      clear
      variant="solid"
      border
    >
      SOLID-BORDER
    </Example>
  </ExampleSection>
);
