import { ExampleSection } from '../../../components/ExampleSection';
import { ExampleUnstyledTransition } from './ExampleUnstyledTransition';

export const VariantExample = () => (
  <ExampleSection title="Variant">
    <ExampleUnstyledTransition
      clear
      variant="none"
    >
      NONE
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="text"
    >
      TEXT
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="plain"
    >
      PLAIN
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="light"
    >
      LIGHT
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="surface"
    >
      SURFACE
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="solid"
    >
      SOLID
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="none"
      border
    >
      NONE-BORDER
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="text"
      border
    >
      TEXT-BORDER
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="plain"
      border
    >
      PLAIN-BORDER
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="light"
      border
    >
      LIGHT-BORDER
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="surface"
      border
    >
      SURFACE-BORDER
    </ExampleUnstyledTransition>
    <ExampleUnstyledTransition
      clear
      variant="solid"
      border
    >
      SOLID-BORDER
    </ExampleUnstyledTransition>
  </ExampleSection>
);
