import type { ComponentConfig } from '../../types';
import type { CardConfigProps } from './Card.types';

export const cardConfig: ComponentConfig<CardConfigProps> = {
  props: {
    as: 'div',
    variant: 'solid',
    orientation: 'col',
    size: 'md',
    radius: 'lg',
    color: 'surface-on',
    shadow: 'md',
    gap: 'unset',
    padding: 'unset',
    px: 'unset',
    py: 'unset',
    pt: 'unset',
    pb: 'unset',
    pl: 'unset',
    pr: 'unset',
    margin: 'unset',
    mx: 'unset',
    my: 'unset',
    mt: 'unset',
    mb: 'unset',
    ml: 'unset',
    mr: 'unset',
    border: 'unset',
    bx: 'unset',
    by: 'unset',
    bt: 'unset',
    bb: 'unset',
    bl: 'unset',
    br: 'unset',
    rt: 'unset',
    rb: 'unset',
    rl: 'unset',
    rr: 'unset',
    rtl: 'unset',
    rtr: 'unset',
    rbl: 'unset',
    rbr: 'unset',
    font: 'unset',
    gx: 'unset',
    gy: 'unset'
  }
};
