import { ExampleCard } from '../../../components/ExampleCard';
import { ExampleSection } from '../../../components/ExampleSection';
import { Navigation } from '../../../core/components/Navigation/Navigation';

export const VariantExample = () => (
  <ExampleSection title="Variant">
    <ExampleCard>
      <Navigation
        variant="text"
        color="primary"
      >
        TEXT
      </Navigation>
      <Navigation
        variant="plain"
        color="primary"
      >
        PLAIN
      </Navigation>
      <Navigation
        variant="light"
        color="primary"
      >
        LIGHT
      </Navigation>
      <Navigation
        variant="surface"
        color="primary"
      >
        SURFACE
      </Navigation>
      <Navigation
        variant="solid"
        color="primary"
      >
        SOLID
      </Navigation>
      <Navigation
        variant="text"
        border
        color="primary"
      >
        TEXT-BORDER
      </Navigation>
      <Navigation
        variant="plain"
        border
        color="primary"
      >
        PLAIN-BORDER
      </Navigation>
      <Navigation
        variant="light"
        border
        color="primary"
      >
        LIGHT-BORDER
      </Navigation>
      <Navigation
        variant="surface"
        border
        color="primary"
      >
        SURFACE-BORDER
      </Navigation>
      <Navigation
        variant="solid"
        border
        color="primary"
      >
        SOLID-BORDER
      </Navigation>
    </ExampleCard>
  </ExampleSection>
);
