import { ExampleCard } from '../../../components/ExampleCard';
import { ExampleSection } from '../../../components/ExampleSection';
import { UnstyledBox } from '../../../core/components/UnstyledBox/UnstyledBox';

export const SizeExample = () => (
  <ExampleSection title="Size">
    <ExampleCard>
      <UnstyledBox
        variant="solid"
        size="none"
        color="primary"
      >
        NONE
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="xs"
        color="primary"
      >
        XS
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="sm"
        color="primary"
      >
        SM
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="md"
        color="primary"
      >
        MD
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="lg"
        color="primary"
      >
        LG
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="xl"
        color="primary"
      >
        XL
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="xxl"
        color="primary"
      >
        XXL
      </UnstyledBox>
    </ExampleCard>
    <ExampleCard>
      <UnstyledBox
        variant="solid"
        size="xs-xs"
        color="primary"
      >
        XS-XS
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="sm-sm"
        color="primary"
      >
        SM-SM
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="md-md"
        color="primary"
      >
        MD-MD
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="lg-lg"
        color="primary"
      >
        LG-LG
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="xl-xl"
        color="primary"
      >
        XL-XL
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        size="xxl-xxl"
        color="primary"
      >
        XXL-XXL
      </UnstyledBox>
    </ExampleCard>
  </ExampleSection>
);
