import { ExampleCard } from '../../../components/ExampleCard';
import { ExampleSection } from '../../../components/ExampleSection';
import { UnstyledBox } from '../../../core/components/UnstyledBox/UnstyledBox';

export const VariantExample = () => (
  <ExampleSection title="Variant">
    <ExampleCard>
      <UnstyledBox
        variant="none"
        color="primary"
      >
        NONE
      </UnstyledBox>
      <UnstyledBox
        variant="text"
        color="primary"
      >
        TEXT
      </UnstyledBox>
      <UnstyledBox
        variant="plain"
        color="primary"
      >
        PLAIN
      </UnstyledBox>
      <UnstyledBox
        variant="light"
        color="primary"
      >
        LIGHT
      </UnstyledBox>
      <UnstyledBox
        variant="surface"
        color="primary"
      >
        SURFACE
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        color="primary"
      >
        SOLID
      </UnstyledBox>
      <UnstyledBox
        variant="none"
        border
        color="primary"
      >
        NONE-BORDER
      </UnstyledBox>
      <UnstyledBox
        variant="text"
        border
        color="primary"
      >
        TEXT-BORDER
      </UnstyledBox>
      <UnstyledBox
        variant="plain"
        border
        color="primary"
      >
        PLAIN-BORDER
      </UnstyledBox>
      <UnstyledBox
        variant="light"
        border
        color="primary"
      >
        LIGHT-BORDER
      </UnstyledBox>
      <UnstyledBox
        variant="surface"
        border
        color="primary"
      >
        SURFACE-BORDER
      </UnstyledBox>
      <UnstyledBox
        variant="solid"
        border
        color="primary"
      >
        SOLID-BORDER
      </UnstyledBox>
    </ExampleCard>
  </ExampleSection>
);
