import { ExampleCard } from '../../../components/ExampleCard';
import { ExampleSection } from '../../../components/ExampleSection';
import { UnstyledFlex } from '../../../core/components/UnstyledFlex/UnstyledFlex';

export const SizeExample = () => (
  <ExampleSection title="Size">
    <ExampleCard>
      <UnstyledFlex
        variant="light"
        size="none"
      >
        NONE
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xs"
      >
        XS
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="sm"
      >
        SM
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="md"
      >
        MD
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="lg"
      >
        LG
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xl"
      >
        XL
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xxl"
      >
        XXL
      </UnstyledFlex>
    </ExampleCard>
    <ExampleCard>
      <UnstyledFlex
        variant="light"
        size="none"
      >
        NONE
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xs-xs"
      >
        XS-XS
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="sm-sm"
      >
        SM-SM
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="md-md"
      >
        MD-MD
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="lg-lg"
      >
        LG-LG
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xl-xl"
      >
        XL-XL
      </UnstyledFlex>
      <UnstyledFlex
        variant="light"
        size="xxl-xxl"
      >
        XXL-XXL
      </UnstyledFlex>
    </ExampleCard>
  </ExampleSection>
);
