import type { AnchorConfigProps } from '../../components/Anchor/Anchor.types';
import type { AppShellConfigProps } from '../../components/AppShell/AppShell.types';
import type { AvatarConfigProps } from '../../components/Avatar/Avatar.types';
import type { AvatarGroupConfigProps } from '../../components/AvatarGroup/AvatarGroup.types';
import type { BadgeConfigProps } from '../../components/Badge/Badge.types';
import type { BoxConfigProps } from '../../components/Box/Box.types';
import type { ButtonConfigProps } from '../../components/Button/Button.types';
import type { CardConfigProps } from '../../components/Card/Card.types';
import type { CardBodyConfigProps } from '../../components/CardBody/CardBody.types';
import type { CardFooterConfigProps } from '../../components/CardFooter/CardFooter.types';
import type { CheckboxConfigProps } from '../../components/Checkbox/Checkbox.types';
import type { ChipConfigProps } from '../../components/Chip/Chip.types';
import type { CircularProgressConfigProps } from '../../components/CircularProgress/CircularProgress.types';
import type { CloseButtonConfigProps } from '../../components/CloseButton/CloseButton.types';
import type { ContainerConfigProps } from '../../components/Container/Container.types';
import type { DividerConfigProps } from '../../components/Divider/Divider.types';
import type { DropdownConfigProps } from '../../components/Dropdown/Dropdown.types';
import type { FabConfigProps } from '../../components/Fab/Fab.types';
import type { FlexConfigProps } from '../../components/Flex/Flex.types';
import type { FooterConfigProps } from '../../components/Footer/Footer.types';
import type { GridConfigProps } from '../../components/Grid/Grid.types';
import type { GroupConfigProps } from '../../components/Group/Group.types';
import type { HeaderConfigProps } from '../../components/Header/Header.types';
import type { IconConfigProps } from '../../components/Icon/Icon.types';
import type { IconButtonConfigProps } from '../../components/IconButton/IconButton.types';
import type { ImageConfigProps } from '../../components/Image/Image.types';
import type { InputConfigProps } from '../../components/Input/Input.types';
import type { LabelConfigProps } from '../../components/Label/Label.types';
import type { LayoutConfigProps } from '../../components/Layout/Layout.types';
import type { LinearProgressConfigProps } from '../../components/LinearProgress/LinearProgress.types';
import type { LinkConfigProps } from '../../components/Link/Link.types';
import type { ListConfigProps } from '../../components/List/List.types';
import type { ListItemConfigProps } from '../../components/ListItem/ListItem.types';
import type { MainConfigProps } from '../../components/Main/Main.types';
import type { MarkConfigProps } from '../../components/Mark/Mark.types';
import type { NavigationConfigProps } from '../../components/Navigation/Navigation.types';
import type { PaperConfigProps } from '../../components/Paper/Paper.types';
import type { RadioConfigProps } from '../../components/Radio/Radio.types';
import type { SectionConfigProps } from '../../components/Section/Section.types';
import type { SidebarConfigProps } from '../../components/Sidebar/Sidebar.types';
import type { SpinnerConfigProps } from '../../components/Spinner/Spinner.types';
import type { StackConfigProps } from '../../components/Stack/Stack.types';
import type { SwitchConfigProps } from '../../components/Switch/Switch.types';
import type { TextConfigProps } from '../../components/Text/Text.types';
import type { TextareaConfigProps } from '../../components/Textarea/Textarea.types';
import type { TitleConfigProps } from '../../components/Title/Title.types';
import type { ToggleButtonConfigProps } from '../../components/ToggleButton/ToggleButton.types';
import type { TransitionConfigProps } from '../../components/Transition/Transition.types';

export type CoreComponentsMap = {
  anchor?: AnchorConfigProps;
  appShell?: AppShellConfigProps;
  avatar?: AvatarConfigProps;
  avatarGroup?: AvatarGroupConfigProps;
  badge?: BadgeConfigProps;
  box?: BoxConfigProps;
  button?: ButtonConfigProps;
  card?: CardConfigProps;
  cardBody?: CardBodyConfigProps;
  cardFooter?: CardFooterConfigProps;
  checkbox?: CheckboxConfigProps;
  chip?: ChipConfigProps;
  circularProgress?: CircularProgressConfigProps;
  closeButton?: CloseButtonConfigProps;
  container?: ContainerConfigProps;
  divider?: DividerConfigProps;
  dropdown?: DropdownConfigProps;
  fab?: FabConfigProps;
  flex?: FlexConfigProps;
  footer?: FooterConfigProps;
  grid?: GridConfigProps;
  group?: GroupConfigProps;
  header?: HeaderConfigProps;
  icon?: IconConfigProps;
  iconButton?: IconButtonConfigProps;
  image?: ImageConfigProps;
  input?: InputConfigProps;
  label?: LabelConfigProps;
  layout?: LayoutConfigProps;
  linearProgress?: LinearProgressConfigProps;
  link?: LinkConfigProps;
  list?: ListConfigProps;
  listItem?: ListItemConfigProps;
  main?: MainConfigProps;
  mark?: MarkConfigProps;
  navigation?: NavigationConfigProps;
  paper?: PaperConfigProps;
  radio?: RadioConfigProps;
  section?: SectionConfigProps;
  sidebar?: SidebarConfigProps;
  spinner?: SpinnerConfigProps;
  stack?: StackConfigProps;
  switch?: SwitchConfigProps;
  text?: TextConfigProps;
  textarea?: TextareaConfigProps;
  title?: TitleConfigProps;
  toggleButton?: ToggleButtonConfigProps;
  transition?: TransitionConfigProps;
};

type ComponentConfig<P> = {
  styles?: string;
  props?: P;
};

type ComponentConfigUtil<T> = {
  [K in keyof T]: ComponentConfig<T[K]>;
};

export type CoreComponentsConfig = ComponentConfigUtil<CoreComponentsMap>;

export type ComponentConfigContext = {
  core?: CoreComponentsConfig;
};
