import type { ComponentConfig } from '../../types';
import type { UnstyledListItemConfigProps } from './UnstyledListItem.types';

export const unstyledListItemConfig: ComponentConfig<UnstyledListItemConfigProps> =
  {
    props: {
      as: 'div',
      variant: 'solid',
      orientation: 'row',
      effect: 'unset',
      componentsProps: {},
      ripple: 'none',
      padding: 'unset',
      p: 'unset',
      px: 'unset',
      py: 'unset',
      pt: 'unset',
      pb: 'unset',
      pl: 'unset',
      pr: 'unset',
      margin: 'unset',
      m: 'unset',
      mx: 'unset',
      my: 'unset',
      mt: 'unset',
      mb: 'unset',
      ml: 'unset',
      mr: 'unset',
      border: 'auto',
      b: 'unset',
      bx: 'unset',
      by: 'unset',
      bt: 'unset',
      bb: 'unset',
      bl: 'unset',
      br: 'unset',
      radius: 'unset',
      r: 'unset',
      rt: 'unset',
      rb: 'unset',
      rl: 'unset',
      rr: 'unset',
      rtl: 'unset',
      rtr: 'unset',
      rbl: 'unset',
      rbr: 'unset',
      font: 'unset',
      color: 'unset',
      shadow: 'unset',
      ring: 'unset',
      gap: 'unset',
      gx: 'unset',
      gy: 'unset'
    }
  };
